(() => {
  const ranks = ['A','K','Q','J'];
  const rankNames = {A:'ACE', K:'KING', Q:'QUEEN', J:'JACK'};
  const suits = ['♠','♥','♦','♣'];
  const players = [
    {name:'你', chips:980, alive:true, hand:[], bullets:0, hidden:false},
    {name:'Raven', chips:880, alive:true, hand:[], bullets:0, hidden:false},
    {name:'Doc', chips:940, alive:true, hand:[], bullets:0, hidden:false},
    {name:'Viper', chips:1000, alive:true, hand:[], bullets:0, hidden:false}
  ];
  let target = 'Q', current = 0, round = 1, chamber = 2, lastClaim = null, muted=false, dragging=false, startX=0, rotZ=0, scale=.92;
  const $ = id => document.getElementById(id);
  const els = {hand:$('handCards'), players:$('playerList'), log:$('log'), target:$('targetRank'), chamber:$('chamberText'), status:$('statusText'), camera:$('camera'), pot:$('potChips'), pile:$('discardPile')};
  function uid(){ return (crypto && crypto.randomUUID) ? crypto.randomUUID() : String(Date.now()+Math.random()); }
  function log(msg, danger=false){ const div=document.createElement('div'); div.className='logItem'+(danger?' danger':''); div.textContent=msg; els.log.prepend(div); while(els.log.children.length>8) els.log.lastChild.remove(); }
  function shuffle(a){ for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; }
  function buildDeck(){ const d=[]; for(let k=0;k<3;k++) for(const r of ranks) for(const s of suits) d.push({id:uid(),r,s}); return shuffle(d); }
  function deal(){ const deck=buildDeck(); players.forEach(p=>p.hand=[]); for(let i=0;i<5;i++) for(const p of players) p.hand.push(deck.pop()); }
  function alivePlayers(){ return players.map((p,i)=>p.alive?i:null).filter(x=>x!==null); }
  function nextPlayer(i){ const live=alivePlayers(); const pos=live.indexOf(i); return live[(pos+1)%live.length]; }
  function renderPlayers(){ els.players.innerHTML=''; players.forEach((p,i)=>{ const div=document.createElement('div'); div.className='player-card '+(i===current?'active ':'')+(!p.alive?'dead':''); div.innerHTML=`<b>${p.name}<span>${p.alive?'等待':'淘汰'}</span></b><small>筹码 ${p.chips} · 手牌 ${p.hand.length} · 风险 ${p.bullets}/6</small><div class="bar"><i style="width:${Math.max(5,100-p.bullets*16)}%"></i></div>`; els.players.appendChild(div); const seat=document.querySelector(`[data-player="${i}"]`); if(seat){ seat.classList.toggle('active',i===current); seat.classList.toggle('dead',!p.alive); } }); }
  function renderHand(){ els.hand.innerHTML=''; players[0].hand.forEach((c,idx)=>{ const div=document.createElement('div'); div.className='card'+(players[0].hidden?' hidden':''); div.dataset.suit=c.s; div.textContent=players[0].hidden?'?':c.r; div.onclick=()=>{ div.classList.toggle('selected'); c.sel=div.classList.contains('selected'); }; els.hand.appendChild(div); }); }
  function renderTable(){ els.target.textContent=rankNames[target]; els.chamber.textContent=`${chamber} / 6`; els.pot.innerHTML=''; for(let i=0;i<28;i++){ const chip=document.createElement('i'); chip.className='chip '+(i%3===0?'gold':i%3===1?'dark':''); chip.style.left=(Math.random()*65-20)+'px'; chip.style.top=(Math.random()*54-18)+'px'; chip.style.transform=`translateZ(${i*1.5}px) rotate(${Math.random()*180}deg)`; els.pot.appendChild(chip); } renderPlayers(); renderHand(); }
  function addPlayedCards(count){ for(let i=0;i<count;i++){ const card=document.createElement('div'); card.className='playedCard'; card.textContent='?'; card.style.left=(Math.random()*38)+'px'; card.style.top=(Math.random()*25)+'px'; card.style.setProperty('--r',(Math.random()*70-35)+'deg'); els.pile.appendChild(card); while(els.pile.children.length>12) els.pile.firstChild.remove(); } }
  function playSelected(){ if(current!==0){ els.status.textContent='还没轮到你。'; return; } let selected=players[0].hand.filter(c=>c.sel); const claimCount=Number($('claimCount').value); if(selected.length===0){ selected=players[0].hand.slice(0,claimCount); } if(selected.length>3) selected=selected.slice(0,3); commitPlay(0, selected); }
  function commitPlay(i, cards){ const p=players[i]; p.hand=p.hand.filter(c=>!cards.includes(c)); const trueCount=cards.filter(c=>c.r===target).length; lastClaim={player:i,cards,trueCount,count:cards.length}; addPlayedCards(cards.length); p.chips=Math.max(0,p.chips-20*cards.length); log(`${p.name} 声明打出 ${cards.length} 张 ${rankNames[target]}。`); if(p.hand.length===0){ log(`${p.name} 已经出完手牌。下一位必须决定是否质疑。`, true); } current=nextPlayer(i); renderTable(); if(current!==0) setTimeout(aiTurn,900); else els.status.textContent='轮到你：出牌、质疑，或观察。'; }
  function challenge(){ if(!lastClaim){ els.status.textContent='还没有可质疑的上一手。'; return; } const liar = lastClaim.trueCount !== lastClaim.count; const loser = liar ? lastClaim.player : current; const winner = liar ? current : lastClaim.player; log(`${players[current].name} 质疑 ${players[lastClaim.player].name}：${liar?'抓到诈唬！':'质疑失败！'}`, true); roulette(loser, winner); lastClaim=null; renderTable(); if(current!==0) setTimeout(aiTurn,950); }
  function roulette(loser, winner){ const p=players[loser]; p.bullets++; const shot = p.bullets >= chamber || Math.random()<0.18; if(shot){ p.alive=false; p.chips=Math.max(0,p.chips-120); players[winner].chips+=120; log(`${p.name} 扣下扳机，中弹淘汰。${players[winner].name} 获得筹码。`, true); } else { p.chips=Math.max(0,p.chips-40); players[winner].chips+=40; log(`${p.name} 空枪，暂时活了下来。`); } if(alivePlayers().length<=1){ const champ=players[alivePlayers()[0]]; log(`${champ.name} 成为最后赢家。点击新一局继续。`, true); els.status.textContent='本局结束。'; } }
  function passTurn(){ if(current!==0){ els.status.textContent='还没轮到你。'; return; } if(lastClaim && players[lastClaim.player].hand.length===0){ log(`你选择不质疑，${players[lastClaim.player].name} 赢下本局。`, true); players[lastClaim.player].chips+=180; return renderTable(); } current=nextPlayer(current); renderTable(); setTimeout(aiTurn,700); }
  function aiTurn(){ if(current===0 || alivePlayers().length<=1) return; const p=players[current]; if(!p.alive){ current=nextPlayer(current); return aiTurn(); } if(lastClaim && Math.random()<(.22 + (lastClaim.count-lastClaim.trueCount)*.22)){ challenge(); return; } const count=Math.min(p.hand.length, Math.ceil(Math.random()*Math.min(3,p.hand.length))); let cards=[]; const truthful=p.hand.filter(c=>c.r===target); if(truthful.length && Math.random()<.55) cards=truthful.slice(0,Math.min(count,truthful.length)); while(cards.length<count){ const c=p.hand.find(x=>!cards.includes(x)); if(!c) break; cards.push(c); } commitPlay(current,cards); }
  function newRound(){ round++; target=shuffle(['A','K','Q'])[0]; chamber=2+Math.floor(Math.random()*4); current=alivePlayers()[0] ?? 0; players.forEach(p=>{p.alive=true;p.bullets=0;p.hand=[]}); lastClaim=null; els.pile.innerHTML=''; deal(); log(`第 ${round} 局开始，目标牌是 ${rankNames[target]}。`); renderTable(); els.status.textContent='新一局开始。'; if(current!==0) setTimeout(aiTurn,800); }
  $('playBtn').onclick=playSelected; $('challengeBtn').onclick=challenge; $('passBtn').onclick=passTurn; $('newRoundBtn').onclick=newRound; $('hideToggle').onclick=()=>{players[0].hidden=!players[0].hidden; renderHand();}; $('muteBtn').onclick=()=>{muted=!muted; $('muteBtn').textContent='酒馆氛围：'+(muted?'关':'开');};
  window.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX}); window.addEventListener('pointerup',()=>dragging=false); window.addEventListener('pointermove',e=>{if(!dragging)return; rotZ+=(e.clientX-startX)*.08; startX=e.clientX; els.camera.style.transform=`translate(-50%,-50%) rotateX(62deg) rotateZ(${rotZ}deg) scale(${scale})`;}); window.addEventListener('wheel',e=>{scale=Math.max(.55,Math.min(1.35,scale-e.deltaY*.0006)); els.camera.style.transform=`translate(-50%,-50%) rotateX(62deg) rotateZ(${rotZ}deg) scale(${scale})`;},{passive:true});
  deal(); log('第 1 局开始，目标牌是 QUEEN。'); renderTable(); els.status.textContent='你先行动：选择手牌后出牌，或者直接诈唬。';
})();
