const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const app = express();
const server = http.createServer(app);
const io = new Server(server);
app.use(express.static('public'));
const PORT = process.env.PORT || 3000;
const rooms = new Map();
const SUITS = ['♠','♥','♦','♣'];
const RANKS = ['2','3','4','5','6','7','8','9','T','J','Q','K','A'];
const VALUE = Object.fromEntries(RANKS.map((r,i)=>[r,i+2]));
function cleanName(x){return String(x||'Player').trim().slice(0,18)||'Player'}
function cardView(c){return c ? {...c, display:(c.rank==='T'?'10':c.rank)+c.suit} : c}
function code(){const s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c='';for(let i=0;i<5;i++)c+=s[Math.floor(Math.random()*s.length)];return c}
function deck(){const d=[];for(const s of SUITS)for(const r of RANKS)d.push({rank:r,suit:s});for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function room(hostId,name){let c;do c=code();while(rooms.has(c));const r={code:c,hostId,players:[newPlayer(hostId,name)],started:false,deck:[],community:[],pot:0,dealerIndex:0,turnIndex:0,currentBet:0,minRaise:20,phase:'lobby',message:'Waiting for players.',smallBlind:10,bigBlind:20,acted:new Set(),winners:[],busted:[],handNumber:0,lastAction:''};rooms.set(c,r);return r}
function newPlayer(id,name){return {id,name,chips:1000,bet:0,total:0,hand:[],folded:false,allIn:false,connected:true,lastScore:null}}
function pub(r,viewer){return {code:r.code,hostId:r.hostId,started:r.started,community:r.community.map(cardView),pot:r.pot,dealerIndex:r.dealerIndex,turnIndex:r.turnIndex,currentBet:r.currentBet,minRaise:r.minRaise,phase:r.phase,message:r.message,smallBlind:r.smallBlind,bigBlind:r.bigBlind,winners:r.winners,busted:r.busted,handNumber:r.handNumber,players:r.players.map((p,i)=>({id:p.id,name:p.name,chips:p.chips,bet:p.bet,total:p.total,hand:p.id===viewer||r.phase==='showdown'?p.hand.map(cardView):p.hand.map(()=>({display:'🂠'})),folded:p.folded,allIn:p.allIn,connected:p.connected,seat:i,isYou:p.id===viewer}))}}
function emit(r){for(const p of r.players)io.to(p.id).emit('state',pub(r,p.id))}
function find(id){for(const r of rooms.values()){const p=r.players.find(x=>x.id===id);if(p)return {r,p}}return null}
function nextChips(r,from){for(let s=1;s<=r.players.length;s++){const i=(from+s)%r.players.length;if(r.players[i].chips>0)return i}return -1}
function nextAble(r,from){for(let s=1;s<=r.players.length;s++){const i=(from+s)%r.players.length,p=r.players[i];if(!p.folded&&!p.allIn&&p.chips>0)return i}return -1}
function active(r){return r.players.filter(p=>!p.folded)}
function able(r){return r.players.filter(p=>!p.folded&&!p.allIn&&p.chips>0)}
function take(p,n){const a=Math.max(0,Math.min(p.chips,n));p.chips-=a;p.bet+=a;p.total+=a;if(p.chips===0)p.allIn=true;return a}
function start(r){if(r.players.filter(p=>p.chips>0).length<2){r.message='Need at least 2 players with chips.';return}r.handNumber++;r.phase='preflop';r.started=true;r.deck=deck();r.community=[];r.pot=0;r.currentBet=r.bigBlind;r.minRaise=r.bigBlind;r.acted=new Set();r.winners=[];r.busted=[];r.players.forEach(p=>{p.hand=[];p.bet=0;p.total=0;p.folded=p.chips<=0;p.allIn=false;p.lastScore=null});for(let k=0;k<2;k++)for(const p of r.players)if(!p.folded)p.hand.push(r.deck.pop());r.dealerIndex%=r.players.length;const sb=nextChips(r,r.dealerIndex),bb=nextChips(r,sb);if(sb<0||bb<0||sb===bb){r.message='Need at least 2 players with chips.';return}take(r.players[sb],r.smallBlind);take(r.players[bb],r.bigBlind);r.currentBet=Math.max(r.players[sb].bet,r.players[bb].bet);r.turnIndex=nextAble(r,bb);if(r.turnIndex<0)r.turnIndex=bb;r.message=`${r.players[sb].name} posts small blind, ${r.players[bb].name} posts big blind.`}
function matched(r){const a=able(r);if(a.length===0)return true;return a.every(p=>p.bet===r.currentBet&&r.acted.has(p.id))}
function endRound(r){for(const p of r.players){r.pot+=p.bet;p.bet=0}r.currentBet=0;r.minRaise=r.bigBlind;r.acted=new Set();if(active(r).length<=1)return finish(r);if(r.phase==='preflop'){r.phase='flop';r.community.push(r.deck.pop(),r.deck.pop(),r.deck.pop());r.message='Flop dealt.'}else if(r.phase==='flop'){r.phase='turn';r.community.push(r.deck.pop());r.message='Turn dealt.'}else if(r.phase==='turn'){r.phase='river';r.community.push(r.deck.pop());r.message='River dealt.'}else return finish(r);r.turnIndex=nextAble(r,r.dealerIndex);if(r.turnIndex<0)finish(r)}
function after(r){if(active(r).length<=1)return finish(r);if(matched(r))return endRound(r);const n=nextAble(r,r.turnIndex);if(n>=0)r.turnIndex=n;else endRound(r)}
function finish(r){for(const p of r.players){r.pot+=p.bet;p.bet=0}r.phase='showdown';let still=r.players.filter(p=>!p.folded),wins=[],best=null;if(still.length===1){wins=[still[0]];wins[0].lastScore={rank:-1,name:'Fold Win',cn:'弃牌胜利',effect:'foldwin',tiebreak:[]};r.message=`${wins[0].name} wins because everyone else folded.`}else{for(const p of still){const sc=evaluate([...p.hand,...r.community]);p.lastScore=sc;if(!best||cmp(sc,best)>0){best=sc;wins=[p]}else if(cmp(sc,best)===0)wins.push(p)}r.message=`${wins.map(w=>w.name).join(', ')} win with ${best.cn}.`}const share=Math.floor(r.pot/wins.length);wins.forEach(w=>w.chips+=share);r.winners=wins.map(w=>({id:w.id,name:w.name,amount:share,handName:w.lastScore.name,handNameCn:w.lastScore.cn,effect:w.lastScore.effect,rank:w.lastScore.rank}));r.busted=r.players.filter(p=>p.chips<=0&&!wins.some(w=>w.id===p.id)).map(p=>({id:p.id,name:p.name}));r.pot=0;r.dealerIndex=nextChips(r,r.dealerIndex);if(r.dealerIndex<0)r.dealerIndex=0}
function vals(cards){return cards.map(c=>VALUE[c.rank]).sort((a,b)=>b-a)}function uniq(v){return [...new Set(v)].sort((a,b)=>b-a)}function straight(v){const u=uniq(v);if(u.includes(14))u.push(1);for(let i=0;i<=u.length-5;i++){const s=u.slice(i,i+5);if(s[0]-s[4]===4&&new Set(s).size===5)return s[0]===1?5:s[0]}return null}
function evaluate(cards){const v=vals(cards),g={};v.forEach(x=>g[x]=(g[x]||0)+1);const ge=Object.entries(g).map(([v,c])=>({v:+v,count:c})).sort((a,b)=>b.count-a.count||b.v-a.v);const suits={};cards.forEach(c=>(suits[c.suit]??=[]).push(VALUE[c.rank]));for(const s in suits)if(suits[s].length>=5){const h=straight(suits[s]);if(h)return{rank:8,tiebreak:[h],name:h===14?'Royal Flush':'Straight Flush',cn:h===14?'皇家同花顺':'同花顺',effect:h===14?'royal':'straightflush'}}const four=ge.find(x=>x.count===4);if(four)return{rank:7,tiebreak:[four.v,v.find(x=>x!==four.v)],name:'Four of a Kind',cn:'四条',effect:'fourkind'};const trips=ge.filter(x=>x.count===3),pairs=ge.filter(x=>x.count===2);if(trips.length&&(pairs.length||trips.length>1))return{rank:6,tiebreak:[trips[0].v,trips.length>1?trips[1].v:pairs[0].v],name:'Full House',cn:'葫芦',effect:'fullhouse'};for(const s in suits)if(suits[s].length>=5)return{rank:5,tiebreak:uniq(suits[s]).slice(0,5),name:'Flush',cn:'同花',effect:'flush'};const st=straight(v);if(st)return{rank:4,tiebreak:[st],name:'Straight',cn:'顺子',effect:'straight'};if(trips.length){const t=trips[0].v;return{rank:3,tiebreak:[t,...v.filter(x=>x!==t).slice(0,2)],name:'Three of a Kind',cn:'三条',effect:'threekind'}}if(pairs.length>=2){const ps=pairs.slice(0,2).map(p=>p.v);return{rank:2,tiebreak:[...ps,v.find(x=>!ps.includes(x))],name:'Two Pair',cn:'两对',effect:'twopair'}}if(pairs.length===1){const p=pairs[0].v;return{rank:1,tiebreak:[p,...v.filter(x=>x!==p).slice(0,3)],name:'One Pair',cn:'一对',effect:'onepair'}}return{rank:0,tiebreak:v.slice(0,5),name:'High Card',cn:'高牌',effect:'highcard'}}
function cmp(a,b){if(a.rank!==b.rank)return a.rank-b.rank;for(let i=0;i<Math.max(a.tiebreak.length,b.tiebreak.length);i++){if((a.tiebreak[i]||0)!==(b.tiebreak[i]||0))return(a.tiebreak[i]||0)-(b.tiebreak[i]||0)}return 0}
io.on('connection',socket=>{socket.on('createRoom',({name},cb)=>{const r=room(socket.id,cleanName(name));socket.join(r.code);cb?.({ok:true,code:r.code});emit(r)});socket.on('joinRoom',({code,name},cb)=>{const r=rooms.get(String(code||'').toUpperCase().trim());if(!r)return cb?.({ok:false,error:'Room not found.'});if(r.phase!=='lobby'&&r.phase!=='showdown')return cb?.({ok:false,error:'Hand already started.'});if(r.players.length>=8)return cb?.({ok:false,error:'Room is full.'});r.players.push(newPlayer(socket.id,cleanName(name)));socket.join(r.code);cb?.({ok:true,code:r.code});emit(r)});socket.on('setPlayerChips',({playerId,chips})=>{const f=find(socket.id);if(!f||f.r.hostId!==socket.id||f.r.phase!=='lobby')return;const p=f.r.players.find(x=>x.id===playerId);const n=Math.max(0,Math.min(999999,Math.floor(Number(chips))));if(p&&Number.isFinite(n)){p.chips=n;emit(f.r)}});socket.on('setAllChips',({chips})=>{const f=find(socket.id);if(!f||f.r.hostId!==socket.id||f.r.phase!=='lobby')return;const n=Math.max(0,Math.min(999999,Math.floor(Number(chips))));if(Number.isFinite(n)){f.r.players.forEach(p=>{p.chips=n;p.bet=0;p.folded=false;p.allIn=false});emit(f.r)}});socket.on('startHand',()=>{const f=find(socket.id);if(!f||f.r.hostId!==socket.id)return;if(f.r.phase!=='lobby'&&f.r.phase!=='showdown')return;start(f.r);emit(f.r)});socket.on('action',({type,amount})=>{const f=find(socket.id);if(!f)return;const r=f.r,p=f.p;if(r.phase==='lobby'||r.phase==='showdown'||r.players[r.turnIndex]?.id!==socket.id||p.folded||p.allIn)return;const call=Math.max(0,r.currentBet-p.bet);if(type==='fold'){p.folded=true;r.acted.add(p.id);r.message=`${p.name} folds.`}else if(type==='check'){if(call!==0)return;r.acted.add(p.id);r.message=`${p.name} checks.`}else if(type==='call'){const paid=take(p,call);r.acted.add(p.id);r.message=`${p.name} calls ${paid}.`}else if(type==='raise'){const target=Math.floor(Number(amount));const raiseBy=target-r.currentBet;if(!Number.isFinite(target)||target<=r.currentBet||raiseBy<r.minRaise)return;take(p,target-p.bet);r.currentBet=p.bet;r.minRaise=Math.max(r.minRaise,raiseBy);r.acted=new Set([p.id]);r.message=`${p.name} raises to ${r.currentBet}.`}else if(type==='allin'){take(p,p.chips);if(p.bet>r.currentBet){r.minRaise=Math.max(r.bigBlind,p.bet-r.currentBet);r.currentBet=p.bet;r.acted=new Set([p.id])}else r.acted.add(p.id);r.message=`${p.name} goes all-in.`}after(r);emit(r)});socket.on('disconnect',()=>{const f=find(socket.id);if(!f)return;f.p.connected=false;f.r.message=`${f.p.name} disconnected.`;emit(f.r)})});
server.listen(PORT,()=>console.log(`Texas Hold'em v4 running at http://localhost:${PORT}`));
